### ISSUE TITLE
test/camera-system

### ISSUE THREAD

**Issue by lbowes** [lbowes/Falcon-9-Simulation#12]
### Description
Write requirements tests for `Cameras` module.

### TODO
- [ ] If no cameras are registered, then the default camera should be active
- [ ] The default camera should be positioned at [0,0,0]
- [ ] If a camera is successfully registered `registerCam` should return true
- [ ] If a camera is registered with an already existing name, `registerCam` should return false (and do nothing)
- [ ] If the user attempts to `bind` a camera that hasn't been `register`ed, `bind` should return false (and do nothing)
- [ ] `bind`ing a camera correctly updates the active camera's position with that of the bound camera
