### ISSUE TITLE
refactor/scene-class

### ISSUE THREAD

**Issue by lbowes** [lbowes/Falcon-9-Simulation#14]
### Description
The `Scene` class needs to be updated.

### TODO
- [x] remove references to Irrlicht from the code, this library is not being used anymore
- [x] make this class a singleton
- [x] add a `draw()` function, responsible for drawing everything in the scene (floor plane grid, skybox, models)
