### ISSUE TITLE
feature/state-snapshot

### ISSUE THREAD

**Issue by lbowes** [lbowes/Falcon-9-Simulation#24]
### Description
A `StateSnapshot` represents the complete state of the simulation at a single instant in time, containing all information the user is interested in. For milestone 1, this is the positions and orientations of both cubes.

### TODO
Create a `StateSnapshot` class containing:
- [x] cube 1 position (`glm::dvec3`)
- [x] cube 1 orientation (`glm::dquat`)
- [x] cube 2 position (`glm::dvec3`)
- [x] cube 2 orientation (`glm::dquat`)

with:

- [x] a constructor that takes in a `json` object (one time point in the simulation output) and parses it to correctly initialise all members
- [x] a static function `lerp` that allows a user to take in two states and linearly interpolate between them, returning the result
