### ISSUE TITLE
refactor/camera-system

### ISSUE THREAD

**Issue by lbowes** [lbowes/Falcon-9-Simulation#28]
### Description
The `CameraSystem` needs small changes.

### TODO
- [x] Convert static variables to members (the class is a singleton, they don't need to be static)
- [x] Update `setViewTransform` to `getViewTransform` and have it return the transform matrix
- [x] Have `Visualisation` call `bgfx::setViewTransform()` with the matrix returned by the `CameraSystem`
- [x] `registerCam` and `bind` should return `bool`s depending on whether they succeed or not
- [x] Add a new public function for getting a list of all registered camera names
