### ISSUE TITLE
feature/obj-model-rendering

### ISSUE THREAD

**Issue by lbowes** [lbowes/Falcon-9-Simulation#3]
### Description
It should be possible to load a basic obj model file using [tinyobjloader](https://github.com/tinyobjloader/tinyobjloader). This model represents an instance of static geometry.

### TODO
- [ ] Create an `OBJModel` class
- [ ] `OBJModel(const char* objFilepath);`
constructor takes in a path to a .obj file

This class should have the following public functions:

- [ ] `void draw(glm::dvec3 camPos) const;`
for getting the model's data on screen
- [ ] `void setTransform(glm::dvec3 position, glm::dquat orientation);`
for updating the world-space transform of this object
