### ISSUE TITLE
fix/fpv-camera-input

### ISSUE THREAD

**Issue by lbowes** [lbowes/Falcon-9-Simulation#44]
### Description
There are a few issues with the way user input is being handled around the `FPVCamera`.

### TODO
- [x] The application should start with the `FPVCamera` already bound (for now)
- [x] Other cameras should not be able to capture mouse focus (with no control, this would do nothing but hide the cursor)
- [x] The `FPVCamera` should not receive any input when it does not have focus
