### ISSUE TITLE
feature/animation-playback-panel

### ISSUE THREAD

**Issue by lbowes** [lbowes/Falcon-9-Simulation#5]
### Description

The visualisation should feature an animation playback panel to allow the user to adjust the time playback configuration of the animation. This system should only be concerned with modifying playback config data (see below).

### TODO
- [ ] Create a `PlaybackControlPanel` class that is given access to a `PlaybackConfig` instance (not owned)
- [ ] Allow the panel to modify the components of the `PlaybackConfig`

Add the following components to the panel:

- [ ] Time slider
- [ ] Pause/resume buttons
- [ ] Speed modifier buttons
- [ ] Jump forward/back buttons
