### ISSUE TITLE
feature/cube-mounted-cam

### ISSUE THREAD

**Issue by lbowes** [lbowes/Falcon-9-Simulation#53]
### Description
The visualisation should contain cameras that are attached to coordinate frames and move with them (future drone camera, interstage camera etc) 

### TODO
- [x] Create a `MountedCamera` and register it with the `CameraSystem`
- [ ] This camera should be fixed on one face of one cube such that the cube is visible in it's FOV
- [ ] This camera should remain fixed to the cube's reference frame as it moves
