### ISSUE TITLE
feature/second-cube

### ISSUE THREAD

**Issue by lbowes** [lbowes/Falcon-9-Simulation#54]
Depends on #51 

### Description
The final app will contain multiple simulated ridid bodies. For milestone 1, one more independent cube mesh should be added to the sim and visualisation. 

### TODO
- [x] Add one more `Mesh` instance to the visualisation
- [x] Create a new cube in the `Simulation`
- [x] The serialised output data for this cube should be nested in a new JSON object at the same level as the first, as if they were 2 components of one parent entity
